# Generated by Django 5.1.4 on 2025-05-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_blog'),
        ('admin_section', '0005_blog'),
    ]

    operations = [
    ]
