# Generated by Django 5.1.4 on 2025-06-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0008_mappedattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='attendance_tracking_description',
            field=models.TextField(blank=True, default='Student attendance tracking allows doctors to mark student presence/absence during training sessions.', help_text='Description of the attendance tracking feature for administrators'),
        ),
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='attendance_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Whether doctors can track student attendance'),
        ),
    ]
