# Generated by Django 5.1.4 on 2025-06-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0009_daterestrictionsettings_attendance_tracking_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterestrictionsettings',
            name='attendance_tracking_description',
        ),
        migrations.RemoveField(
            model_name='daterestrictionsettings',
            name='attendance_tracking_enabled',
        ),
    ]
