# Generated by Django 5.1.4 on 2025-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0010_remove_daterestrictionsettings_attendance_tracking_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='allowed_days_for_doctors',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated list of allowed days of week for doctors (0=Monday, 6=Sunday)', max_length=20),
        ),
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='allowed_days_for_students',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated list of allowed days of week for students (0=Monday, 6=Sunday)', max_length=20),
        ),
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='doctor_allow_future_dates',
            field=models.BooleanField(default=False, help_text='Whether doctors can review future-dated logs'),
        ),
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='doctor_future_days_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of days in the future a doctor can review logs (if future dates are allowed)'),
        ),
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='doctor_past_days_limit',
            field=models.PositiveIntegerField(default=30, help_text='Maximum number of days in the past a doctor can review logs'),
        ),
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether date restrictions are active'),
        ),
    ]
