# Generated by Django 5.1.4 on 2025-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0011_daterestrictionsettings_allowed_days_for_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterestrictionsettings',
            name='attendance_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Whether doctors can track student attendance'),
        ),
    ]
