# Generated by Django 5.1.4 on 2025-01-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogYearSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_section_name', models.CharField(max_length=20, unique=True)),
                ('year_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogYear', to='publicpage.logyear')),
            ],
        ),
    ]
