# Generated by Django 5.1.4 on 2025-01-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='log_year_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='publicpage.logyearsection'),
        ),
    ]
