# Generated by Django 5.1.4 on 2025-03-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctor_departments_alter_student_group'),
        ('publicpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='log_year',
        ),
        migrations.RemoveField(
            model_name='group',
            name='log_year_section',
        ),
        migrations.RemoveField(
            model_name='trainingsite',
            name='log_year',
        ),
        migrations.RemoveField(
            model_name='logyearsection',
            name='year_name',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TrainingSite',
        ),
        migrations.DeleteModel(
            name='LogYear',
        ),
        migrations.DeleteModel(
            name='LogYearSection',
        ),
    ]
