# Generated by Django 5.1.4 on 2025-01-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpage', '0002_department_log_year_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('log_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sites', to='publicpage.logyear')),
            ],
        ),
    ]
