# Generated by Django 5.1.4 on 2025-02-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpage', '0003_trainingsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='city',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.AddField(
            model_name='doctor',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='publicpage.department'),
        ),
        migrations.AlterField(
            model_name='logyearsection',
            name='year_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_year_sections', to='publicpage.logyear'),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
