# Generated by Django 5.1.4 on 2025-02-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpage', '0004_remove_doctor_city_remove_doctor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
