# Generated by Django 5.1.4 on 2025-03-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corediaprosession',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='corediaprosession',
            name='department',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
        migrations.DeleteModel(
            name='CoreDiaProSession',
        ),
    ]
