# Generated by Django 5.1.4 on 2025-04-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_section', '0005_studentlogformmodel_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogformmodel',
            name='reviewer',
        ),
    ]
