# Generated by Django 5.1.4 on 2025-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_section', '0007_studentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogformmodel',
            name='patient_age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentlogformmodel',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
