# Generated by Django 5.1.4 on 2025-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_section', '0008_studentlogformmodel_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogformmodel',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
