# Generated by Django 5.1.4 on 2025-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_section', '0009_alter_studentlogformmodel_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogformmodel',
            name='review_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline by which the doctor must review this log', null=True),
        ),
    ]
