services:
  - type: web
    name: elogbookagu
    env: python
    plan: free
    buildCommand: |
      cd elogbookagu
      pip install -r ../requirements.txt
    startCommand: gunicorn elogbookagu.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: elogbookagu.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
