# Generated by Django 5.1.4 on 2025-04-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_doctor_departments_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20)),
                ('admin_comments', models.TextField(blank=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Support Ticket',
                'verbose_name_plural': 'Doctor Support Tickets',
                'ordering': ['-date_created'],
            },
        ),
    ]
