# Generated by Django 5.1.4 on 2025-02-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
