# Generated by Django 5.1.4 on 2025-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctor_departments_alter_student_group'),
        ('admin_section', '0002_department_logyear_alter_activitytype_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='staff', to='admin_section.department'),
        ),
    ]
