# Generated by Django 5.1.4 on 2025-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_departments'),
        ('admin_section', '0002_department_logyear_alter_activitytype_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(to='admin_section.department'),
        ),
    ]
